<a href="https://colab.research.google.com/github/surajsarkar3526-cyber/AI-Research-Scientist-Engineer/blob/main/pandas_String.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# What are vectorized operation
a = np.array([1,2,3,4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a * 4

array([ 4,  8, 12, 16])

In [ ]:
# problem in vectorized operation in venilla python
s = ['cat','mat','rat']

[i.startswith('c') for i in s]

[True, False, False]

In [ ]:
[i.startswith('c') for i in s]

[True, False, False]

In [ ]:
# How pandas solves this issue?

s = pd.Series(['cat','mat',None,'rat'])
s.str.startswith('c')

# fast and optimized

0     True
1    False
2     None
3    False
dtype: object

In [ ]:
# import titanic
df = pd.read_csv('/content/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# common Functions
# lower/upper/capitalize/title
df['Name'].str.lower()
df['Name'].str.upper()
df['Name'].str.capitalize()
df['Name'].str.title()
# len
df['Name'].str.len()
df['Name'][df['Name'].str.len() == 82].values[0]
# strip
"           Son     ".strip()

'Son'

In [ ]:
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# strip -> get
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
df['LastName'] = df['Name'].str.split(',').str.get(0)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,LastName
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen

In [ ]:
df[['title','firstname']] = df['Name'].str.split(',').str.get(1).str.strip().str.split(' ', n=1, expand = True)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,LastName,title,firstname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry

In [ ]:
df['title'].value_counts()

title
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Col.           2
Mlle.          2
Major.         2
Ms.            1
Mme.           1
Don.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [ ]:
df['title'] = df['title'].str.replace('Mr.','Miss')
df['title'] = df['title'].str.replace('Mlle','Miss')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,LastName,title,firstname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Miss,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Miss,William Henry

In [ ]:
# filtering
# startswith/endswith
df[df['firstname'].str.startswith('A')]
df[df['firstname'].str.endswith('z')]
# isdigit/isalpha....
df[df['firstname'].str.isdigit()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, LastName, title, firstname]
Index: []

In [ ]:
# applying regex
# contains
# search john -> both case
df[df['firstname'].str.contains('john',case=False)]
# find lastnames with start and end char vowel
df[df['firstname'].str.contains('^[aeiouAEIOU].+[aeiouAEIOU]$')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,LastName,title,firstname
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q,Rice,Master.,Eugene
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.00,2,0,345764,18.0000,NaN,S,Vander Planke,Miss.,Augusta Maria
61,62,1,1,"Icard, Miss. Amelie",female,38.00,0,0,113572,80.0000,B28,NaN,Icard,Miss.,Amelie
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C,Stewart,Miss,Albert A
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S,Andersson,Miss.,Erna Alexandra
80,81,0,3,"Waelens, Mr. Achille",male,22.00,0,0,345767,9.0000,NaN,S,Waelens,Miss,Achille
106,107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21.00,0,0,343120,7.6500,NaN,S,Salkjelsvik,Miss.,Anna Kristine
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S,Andersson,Miss.,Ellis Anna Maria
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C,Peter,Miss.,Anna
135,136,0,2,"Richard, Mr. Emile",male,23.00,0,0,SC/PARIS 2133,15.0458,NaN,C,Richard,Miss,Emile
141,142,1,3,"Nysten, Miss. Anna Sofia",female,22.00,0,0,347081,7.7500,NaN,S,Nysten,Miss.,Anna Sofia
152,153,0,3,"Meo, Mr. Alfonzo",male,55.50,0,0,A.5. 11206,8.0500,NaN,S,Meo,Miss,Alfonzo
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,Panula,Master.,Eino Viljami
195,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C,Lurette,Miss.,Elise
216,217,1,3,"Honkanen, Miss. Eliina",female,27.00,0,0,STON/O2. 3101283,7.9250,NaN,S,Honkanen,Miss.,Eliina
218,219,1,1,"Bazzani, Miss. Albina",female,32.00,0,0,11813,76.2917,D15,C,Bazzani,Miss.,Albina
235,236,0,3,"Harknett, Miss. Alice Phoebe",female,NaN,0,0,W./C. 6609,7.5500,NaN,S,Harknett,Miss.,Alice Phoebe
246,247,0,3,"Lindahl, Miss. Agda Thorilda Viktoria",female,25.00,0,0,347071,7.7750,NaN,S,Lindahl,Miss.,Agda Thorilda Viktoria
258,259,1,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C,Ward,Miss.,Anna
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S,Bissette,Miss.,Amelia
276,277,0,3,"Lindblom, Miss. Augusta Charlotta",female,45.00,0,0,347073,7.7500,NaN,S,Lindblom,Miss.,Augusta Charlotta
293,294,0,3,"Haas, Miss. Aloisia",female,24.00,0,0,349236,8.8500,NaN,S,Haas,Miss.,Aloisia
298,299,1,1,"Saalfeld, Mr. Adolphe",male,NaN,0,0,19988,30.5000,C106,S,Saalfeld,Miss,Adolphe
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,Ryerson,Miss.,Emily Borie
363,364,0,3,"Asim, Mr. Adola",male,35.00,0,0,SOTON/O.Q. 3101310,7.0500,NaN,S,Asim,Miss,Adola
368,369,1,3,"Jermyn, Miss. Annie",female,NaN,0,0,14313,7.7500,NaN,Q,Jermyn,Miss.,Annie
376,377,1,3,"Landergren, Miss. Aurora Adelia",female,22.00,0,0,C 7077,7.2500,NaN,S,Landergren,Miss.,Aurora Adelia
396,397,0,3,"Olsson, Miss. Elina",female,31.00,0,0,350407,7.8542,NaN,S,Olsson,Miss.,Elina
409,410,0,3,"Lefebre, Miss. Ida",female,NaN,3,1,4133,25.4667,NaN,S,Lefebre,Miss.,Ida
474,475,0,3,"Strandberg, Miss. Ida Sofia",female,22.00,0,0,7553,9.8375,NaN,S,Strandberg,Miss.,Ida Sofia
520,521,1,1,"Perreault, Miss. Anne",female,30.00,0,0,12749,93.5000,B73,S,Perreault,Miss.,Anne
541,542,0,3,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,347082,31.2750,NaN,S,Andersson,Miss.,Ingeborg Constanzia
566,567,0,3,"Stoytcheff, Mr. Ilia",male,19.00,0,0,349205,7.8958,NaN,S,Stoytcheff,Miss,Ilia
615,616,1,2,"Herman, Miss. Alice",female,24.00,1,2,220845,65.0000,NaN,S,Herman,Miss.,Alice
620,621,0,3,"Yasbeck, Mr. Antoni",male,27.00,1,0,2659,14.4542,NaN,C,Yasbeck,Miss,Antoni
641,642,1,1,"Sagesser, Mlle. Emma",female,24.00,0,0,PC 17477,69.3000,B35,C,Sagesser,Miss.,Emma
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C,Baclini,Miss.,Eugenie
649,650,1,3,"Stanley, Miss. Amy Zillah Elsie",female,23.00,0,0,CA. 2314,7.5500,NaN,S,Stanley,Miss.,Amy Zillah Elsie
651,652,1,2,"Doling, Miss. Elsie",female,18.00,0,1,231919,23.0000,NaN,S,Doling,Miss.,Elsie
677,678,1,3,"Turja, Miss. Anna Sofia",female,18.00,0,0,4138,9.8417,NaN,S,Turja,Miss.,Anna Sofia
692,693,1,3,"Lam, Mr. Ali",male,NaN,0,0,1601,56.4958,NaN,S,Lam,Miss,Ali
708,709,1,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S,Cleaver,Miss.,Alice
747,748,1,2,"Sinkkonen, Miss. Anna",female,30.00,0,0,250648,13.0000,NaN,S,Sinkkonen,Miss.,Anna
761,762,0,3,"Nirva, Mr. Iisakki Antino Aijo",male,41.00,0,0,SOTON/O2 3101272,7.1250,NaN,S,Nirva,Miss,Iisakki Antino Aijo
786,787,1,3,"Sjoblom, Miss. Anna Sofia",female,18.00,0,0,3101265,7.4958,NaN,S,Sjoblom,Miss.,Anna Sofia
807,808,0,3,"Pettersson, Miss. Ellen Natalia",female,18.00,0,0,347087,7.7750,NaN,S,Pettersson,Miss.,Ellen Natalia
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,31.2750,NaN,S,Andersson,Miss.,Ebba Iris Alfrida
814,815,0,3,"Tomlin, Mr. Ernest Portage",male,30.50,0,0,364499,8.0500,NaN,S,Tomlin,Miss,Ernest Portage
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C,Mallet,Master.,Andre
834,835,0,3,"Allum, Mr. Owen George",male,18.00,0,0,2223,8.3000,NaN,S,Allum,Miss,Owen George
842,843,1,1,"Serepeca, Miss. Augusta",female,30.00,0,0,113798,31.0000,NaN,C,Serepeca,Miss.,Augusta

In [ ]:
# slicing
df['Name'].str[::4]

0             BnMO r
1      Cn .hreFe gTe
2             Hkni n
3        Fe,saee lae
4             Anriae
           ...
886           Mv,vus
887          GaM.red
888       Js,sCeel"r
889           B,.rol
890            DeMPi
Name: Name, Length: 891, dtype: object

In [ ]:
df['Name'].str[::-1]

0                                sirraH newO .rM ,dnuarB
1      )reyahT sggirB ecnerolF( yeldarB nhoJ .srM ,sg...
2                                 aniaL .ssiM ,nenikkieH
3           )leeP yaM yliL( htaeH seuqcaJ .srM ,ellertuF
4                               yrneH mailliW .rM ,nellA
                             ...
886                                sazouJ .veR ,alivtnoM
887                         htidE teragraM .ssiM ,maharG
888             "eirraC" neleH enirehtaC .ssiM ,notsnhoJ
889                                llewoH lraK .rM ,rheB
890                                  kcirtaP .rM ,yelooD
Name: Name, Length: 891, dtype: object